<?php
$form = $this->form;
?>
<?php if ( ! empty( $form ) ) : ?>
<?php echo stripslashes( $form ); ?>
<?php else : ?>
<form class="container" action="https://<?php echo $this->domain; ?>.sendsmaily.net/api/opt-in/" method="post">
	<div>
		<input type="hidden" name="key" value="<?php echo $this->key; ?>" />
		<input type="hidden" name="autoresponder" value="<?php echo $this->autoresponder; ?>" />
		<?php if ( ! empty( $success_url ) ) : ?>
		<input type="hidden" name="success_url" value="<?php echo $success_url; ?>" />
		<?php endif;?>
		<?php if ( ! empty( $failure_url ) ) : ?>
		<input type="hidden" name="failure_url" value="<?php echo $failure_url; ?>" />
		<?php endif; ?>
	</div>
	
	<p>
		<label><?php echo __( 'Email', 'wp_sendsmaily' ); ?></label>
		<input type="text" name="email" value="" />
	</p>
	<p>
		<label><?php echo __( 'Name', 'wp_sendsmaily' ); ?></label>
		<input type="text" name="name" value="" />
	</p>
	
	<p>
		<button type="submit"><?php echo __( 'Subscribe', 'wp_sendsmaily' ); ?></button>
	</p>
</form>
<?php endif; ?>
