<?php
$success_url = $this->success_url;
$failure_url = $this->failure_url;
?>
<form class="container" action="<?php echo SS_PLUGIN_URL; ?>/subscribe.php" method="post">
	<?php if ( ! empty( $success_url ) or ! empty( $failure_url ) ) : ?>
	<div>
		<?php if ( ! empty( $success_url ) ) : ?>
		<input type="hidden" name="success_url" value="<?php echo $success_url; ?>" />
		<?php endif;?>
		<?php if ( ! empty( $failure_url ) ) : ?>
		<input type="hidden" name="failure_url" value="<?php echo $failure_url; ?>" />
		<?php endif; ?>
	</div>
	<?php endif; ?>
	<p>
		<label><?php echo __( 'Email', 'wp_sendsmaily' ); ?></label>
		<input type="text" name="email" value="" />
	</p>
	<p>
		<label><?php echo __( 'Name', 'wp_sendsmaily' ); ?></label>
		<input type="text" name="name" value="" />
	</p>
	
	<p>
		<button type="submit"><?php echo __( 'Subscribe', 'wp_sendsmaily' ); ?></button>
	</p>
</form>
