<form id="smly" class="container" action="<?php echo SS_PLUGIN_URL; ?>/subscribe.php" method="post">
	<p class="error" style="padding:15px;background-color:#f2dede;margin:0 0 10px;display:none"></p>
	<p class="success" style="padding:15px;background-color:#dff0d8;margin:0 0 10px;display:none">Thank you for subscribing to our newsletter.</p>

	<p><input type="text" name="email" value="" placeholder="<?php echo esc_html__( 'Email', 'wp_sendsmaily' ); ?>" /></p>

	<?php if ( $this->show_name ) : ?>
		<p>
			<label><?php echo esc_html__( 'Name', 'wp_sendsmaily' ); ?></label>
			<input type="text" name="name" value="" />
		</p>
	<?php endif; ?>
	
	<p><button type="submit"><?php echo esc_html__( 'Subscribe', 'wp_sendsmaily' ); ?></button></p>
</form>
