<?php
$key = $this->key;
$autoresponders = $this->autoresponders;
?>

<div>
	<input type="hidden" name="op" value="save" />
	<input type="hidden" name="is_advanced" value="0" />
</div>

<?php if ( ! empty( $key ) ) : ?>
<p>
	<span><?php echo esc_html__( 'Your current API key is', 'wp_sendsmaily' ); ?> <strong><?php echo $this->key; ?></strong></span>
	<a href="#" onclick="javascript:Default.removeApiKey();return false;"><img src="<?php echo SS_PLUGIN_URL; ?>/gfx/remove.png" alt="<?php echo esc_html__( 'Remove', 'wp_sendsmaily' ); ?>" title="<?php echo esc_html__( 'Remove', 'wp_sendsmaily' ); ?>" /></a>
</p>
<?php else : ?>
<p>
	<?php echo esc_html__( 'API key', 'wp_sendsmaily' ); ?> <input type="text" class="regular-text" name="key" style="width:300px" />
	<input type="button" value="<?php echo esc_html__( 'Check', 'wp_sendsmaily' ); ?>" name="Submit" class="button-primary" onclick="javascript:Default.validateApiKey();return false;" />
</p>
<?php endif; ?>

<?php if ( ! empty( $key ) ) : ?>
<ul class="tabs">
	<li><a id="link-basic" href="#basic" class="selected"><?php echo esc_html__( 'Basic', 'wp_sendsmaily' ); ?></a></li>
	<li><a id="link-advanced" href="#advanced"><?php echo esc_html__( 'Advanced', 'wp_sendsmaily' ); ?></a></li>
</ul>
<div class="clear"></div>

<div id="content-basic" class="tab-content">
	<div class="wrap">
		<label><?php echo esc_html__( 'Autoresponders', 'wp_sendsmaily' ); ?> <a href="#" onclick="javascript:Default.refreshAutoresp();return false;">(<?php echo esc_html__( 'Refresh', 'wp_sendsmaily' ); ?>)</a></label>
		<em><?php echo esc_html__( 'Please select your opt-in autoresponder', 'wp_sendsmaily' ); ?></em>
		<?php if ( ! empty( $autoresponders ) ) : ?>
		<select name="basic[autoresponder]">
			<?php foreach ( $this->autoresponders as $item ) : ?>
			<option value="<?php echo $item->id; ?>"<?php if ( $this->autoresponder == $item->id ) : ?> selected="selected"<?php endif; ?>><?php echo $item->title; ?></option>
			<?php endforeach; ?>
		</select>
		<?php else : ?>
		<span><?php echo esc_html__( 'No autoresponders. Please click on refresh link to update.', 'wp_sendsmaily' ); ?></span>
		<?php endif; ?>
	</div>
</div>

<div id="content-advanced" class="tab-content hidden">
	<div class="wrap">
		<label><?php echo esc_html__( 'Newsletter subscription form', 'wp_sendsmaily' ); ?> <a href="#" onclick="javascript:Default.resetForm();return false;" title="<?php echo esc_html__( 'Restore original subscription form', 'wp_sendsmaily' ); ?>">(<?php echo esc_html__( 'Regenerate', 'wp_sendsmaily' ); ?>)</a></label>
		<em><?php echo esc_html__( 'HTML of subscription form', 'wp_sendsmaily' ); ?></em>
		<textarea id="advanced-form" name="advanced[form]" rows="15"><?php echo stripslashes( $this->form ); ?></textarea>
	</div>
</div>

<p style="font-size:10px"><?php echo esc_html__( 'Note: When you save under Basic tab, default form will be used.', 'wp_sendsmaily' ); ?></p>

<div class="wrap">
	<input type="button" value="<?php echo esc_html__( 'Save changes', 'wp_sendsmaily' ); ?>" name="Submit" class="button-primary" onclick="javascript:Default.save();return false;" />
</div>
<?php endif; ?>

<script type="text/javascript">//<![CDATA[
  new Tabs({'target':'ul.tabs'});
  jQuery('#link-basic').click(function(){
	  jQuery('input[name=is_advanced]').val('0');
  });
  jQuery('#link-advanced').click(function(){
	  jQuery('input[name=is_advanced]').val('1');
  });
//]]></script>
