<?php
/**
 * This file is part of Sendsmaily Wordpress plugin.
 * 
 * Sendsmaily Wordpress plugin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Sendsmaily Wordpress plugin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Sendsmaily Wordpress plugin.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

		<div>
			<input type="hidden" name="op" value="save" />
			<input type="hidden" name="is_advanced" value="0" />
		</div>

		<?php $key = $this->key; ?>
		<?php if(!empty($key)): ?>
		<p>
			<span><?php echo __('Your current API key is', 'wp_sendsmaily'); ?> <strong><?php echo $this->key; ?></strong></span>
			<a href="#" onclick="javascript:Default.removeApiKey();return false;"><img src="<?php echo SS_PLUGIN_URL; ?>gfx/remove.png" alt="<?php echo __('Remove', 'wp_sendsmaily'); ?>" title="<?php echo __('Remove', 'wp_sendsmaily'); ?>" /></a>
		</p>
		<?php else: ?>
		<p>
			<?php echo __('Please, insert API key here', 'wp_sendsmaily'); ?> <input type="text" class="regular-text" name="key" style="width:300px" />
			<input type="button" value="<?php echo __('Check', 'wp_sendsmaily'); ?>" name="Submit" class="button-primary" onclick="javascript:Default.validateApiKey();return false;" />
		</p>
		<?php endif; ?>
		
		<?php if(!empty($key)): ?>
		<ul class="tabs">
			<li><a id="link-basic" href="#basic" class="selected"><?php echo __('Basic', 'wp_sendsmaily'); ?></a></li>
			<li><a id="link-advanced" href="#advanced"><?php echo __('Advanced', 'wp_sendsmaily'); ?></a></li>
		</ul>
		<div class="clear"></div>
		
		<div id="content-basic" class="tab-content">
			<div class="wrap">
				<label><?php echo __('Autoresponders', 'wp_sendsmaily'); ?> <a href="#" onclick="javascript:Default.refreshAutoresp();return false;">(<?php echo __('Refresh', 'wp_sendsmaily'); ?>)</a></label>
				<em><?php echo __('Please select your opt-in autoresponder', 'wp_sendsmaily'); ?></em>
				<?php
				$autoresponders = $this->autoresponders;
				if(!empty($autoresponders)):
				?>
				<select name="basic[autoresponder]">
					<?php foreach($this->autoresponders as $item): ?>
					<option value="<?php echo $item->id; ?>"<?php if($this->autoresponder == $item->id): ?> selected="selected"<?php endif; ?>><?php echo $item->title; ?></option>
					<?php endforeach; ?>
				</select>
				<?php else: ?>
				<span><?php echo __('No autoresponders. Please click on refresh link to update.', 'wp_sendsmaily'); ?></span>
				<?php endif; ?>
			</div>
		
			<div class="wrap">
				<label><?php echo __('Success URL', 'wp_sendsmaily'); ?></label>
				<em><?php echo __('Address where subscribers will be directed after successful subscription', 'wp_sendsmaily'); ?></em>
				<input type="text" class="input-text" name="basic[success_url]" value="<?php echo $this->success_url; ?>" />
			</div>
			
			<div class="wrap">
				<label><?php echo __('Failure URL', 'wp_sendsmaily'); ?></label>
				<em><?php echo __('Address where subscribers will be directed after failure', 'wp_sendsmaily'); ?></em>
				<input type="text" class="input-text" name="basic[failure_url]" value="<?php echo $this->failure_url; ?>" />
			</div>
		</div>
		
		<div id="content-advanced" class="tab-content hidden">
			<div class="wrap">
				<label><?php echo __('Newsletter subscription form', 'wp_sendsmaily'); ?> <a href="#" onclick="javascript:Default.resetForm();return false;" title="<?php echo __('Restore original subscription form', 'wp_sendsmaily'); ?>">(<?php echo __('Regenerate', 'wp_sendsmaily'); ?>)</a></label>
				<em><?php echo __('HTML of subscription form', 'wp_sendsmaily'); ?></em>
				<textarea id="advanced-form" name="advanced[form]" rows="15"><?php echo stripslashes($this->form); ?></textarea>
			</div>
		</div>
		
		<p style="font-size:10px"><?php echo __('Note: When you save under Basic tab, default form will be used.', 'wp_sendsmaily'); ?></p>
		
		<div class="wrap">
			<input type="button" value="<?php echo __('Save changes', 'wp_sendsmaily'); ?>" name="Submit" class="button-primary" onclick="javascript:Default.save();return false;" />
		</div>
		<?php endif; ?>
		
		<script type="text/javascript">//<![CDATA[
		  new Tabs({'target':'ul.tabs'});
		  jQuery('#link-basic').click(function(){
			  jQuery('input[name=is_advanced]').val('0');
		  });
		  jQuery('#link-advanced').click(function(){
			  jQuery('input[name=is_advanced]').val('1');
		  });
		//]]></script>